apiVersion: v1
kind: Secret
metadata:
  name: autodeploy-lab-secret
  namespace: autodeploy
type: Opaque
data:
  SECRET_KEY: c2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  DB_PASSWORD: ZGJwYXNzd29yZDEyMw==